name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.3
      with:
        # Folder to check syntax
        dir: .
    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v1.0.0
      with:
        # Configuration file location
        config: phpunit.xml
